---
- name: 'Add entries to hosts file'
  loop: '{{ hosts }}'
  lineinfile:
    path: '/etc/hosts'
    line: '{{ hostvars[item].ansible_host }} {{ item }}.{{ domain }} {{ item }}'
...
# vim: set filetype=yaml
